services:

  app-sd:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-sd:
        condition: service_started
    ports:
      - "18080:8080"  # http://localhost:18080/ejb/ShowCount
    networks:
      - sd

  mysql-sd:
    container_name: "mysql-sd"
    image: mysql:latest
    environment:
#      - DB_NAME=${DB_NAME}
#      - DB_USER=bm_dev
      MYSQL_DATABASE: db-sd
      MYSQL_USER: bm_dev
      MYSQL_PASSWORD: bm_dev
      MYSQL_USER_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - mysql-dumps:/dump
    ports:
      - "13306:3306"
    networks:
      - sd


volumes:
  mysql:
  mysql-dumps:
    driver: local

networks:
  sd:

#  docker run -p 11306:113306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=db-sd mysql:8.0.0